version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: fedi
      POSTGRES_DB: fedi
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
